/**
 * Refusal-code catalogue and disclosure-policy implementation.
 *
 * The catalogue is hardcoded here from refusals/catalogue.v1.yaml. If the
 * YAML changes, regenerate this file. A future version will load the YAML
 * at runtime.
 */

export enum RefusalCode {
  // request_shape
  MALFORMED_REQUEST = "MALFORMED_REQUEST",
  UNSUPPORTED_PROTOCOL_VERSION = "UNSUPPORTED_PROTOCOL_VERSION",
  CANONICALISATION_FAILURE = "CANONICALISATION_FAILURE",
  // proof_presence
  PROOF_MISSING = "PROOF_MISSING",
  // proof_validity
  PROOF_INVALID = "PROOF_INVALID",
  ISSUER_UNTRUSTED = "ISSUER_UNTRUSTED",
  SIGNATURE_INVALID = "SIGNATURE_INVALID",
  PROOF_EXPIRED = "PROOF_EXPIRED",
  PROOF_NOT_YET_VALID = "PROOF_NOT_YET_VALID",
  AUDIENCE_MISMATCH = "AUDIENCE_MISMATCH",
  TARGET_MISMATCH = "TARGET_MISMATCH",
  ACTION_MISMATCH = "ACTION_MISMATCH",
  PARAMETER_MISMATCH = "PARAMETER_MISMATCH",
  REPLAY_DETECTED = "REPLAY_DETECTED",
  // authority_state
  AUTHORITY_REVOKED = "AUTHORITY_REVOKED",
  POLICY_REFUSAL = "POLICY_REFUSAL",
  // provider
  CREDENTIAL_UNAVAILABLE = "CREDENTIAL_UNAVAILABLE",
  PROVIDER_REFUSAL = "PROVIDER_REFUSAL",
  PROVIDER_FAILURE = "PROVIDER_FAILURE",
  // outcome
  OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN",
}

export enum DisclosurePolicy {
  PUBLIC = "public",
  TRUSTED = "trusted",
  LOCAL_DEBUG = "local_debug",
}

export const PUBLIC_SAFE_CODES: ReadonlySet<string> = new Set([
  "MALFORMED_REQUEST",
  "UNSUPPORTED_PROTOCOL_VERSION",
  "CANONICALISATION_FAILURE",
  "PROOF_MISSING",
  "PROOF_INVALID",
  "PROOF_EXPIRED",
  "PROOF_NOT_YET_VALID",
  "REPLAY_DETECTED",
  "AUTHORITY_REVOKED",
  "POLICY_REFUSAL",
  "CREDENTIAL_UNAVAILABLE",
  "PROVIDER_REFUSAL",
  "PROVIDER_FAILURE",
  "OUTCOME_UNKNOWN",
]);

export const DETAILED_CODES: ReadonlySet<string> = new Set([
  "MALFORMED_REQUEST",
  "UNSUPPORTED_PROTOCOL_VERSION",
  "CANONICALISATION_FAILURE",
  "PROOF_MISSING",
  "PROOF_INVALID",
  "ISSUER_UNTRUSTED",
  "SIGNATURE_INVALID",
  "PROOF_EXPIRED",
  "PROOF_NOT_YET_VALID",
  "AUDIENCE_MISMATCH",
  "TARGET_MISMATCH",
  "ACTION_MISMATCH",
  "PARAMETER_MISMATCH",
  "REPLAY_DETECTED",
  "AUTHORITY_REVOKED",
  "POLICY_REFUSAL",
  "CREDENTIAL_UNAVAILABLE",
  "PROVIDER_REFUSAL",
  "PROVIDER_FAILURE",
  "OUTCOME_UNKNOWN",
]);

export const COMPATIBILITY_ALIASES: Readonly<Record<string, string>> = {
  // Kernel FailureCode enum members
  PCCB_REQUIRED: "PROOF_MISSING",
  PCCB_EXPIRED: "PROOF_EXPIRED",
  DUPLICATE_REPLAY: "REPLAY_DETECTED",
  SIGNATURE_INVALID: "SIGNATURE_INVALID",
  ACTION_MISMATCH: "ACTION_MISMATCH",
  AUDIENCE_MISMATCH: "AUDIENCE_MISMATCH",
  // Kernel refusal-code strings
  PROOF_INVALID: "PROOF_INVALID",
  INTENT_MISMATCH: "PARAMETER_MISMATCH",
  TARGET_MISMATCH: "TARGET_MISMATCH",
  ACTION_HASH_MISMATCH: "PARAMETER_MISMATCH",
  ACTION_HASH_ALGORITHM_INVALID: "PARAMETER_MISMATCH",
  ACTION_HASH_INVALID: "PARAMETER_MISMATCH",
  SCOPE_MODE_INVALID: "PARAMETER_MISMATCH",
  SCOPE_CAPABILITY_MISMATCH: "PARAMETER_MISMATCH",
  TENANT_MISMATCH: "TARGET_MISMATCH",
  SUBJECT_MISMATCH: "TARGET_MISMATCH",
  PROOF_PAYLOAD_INVALID: "MALFORMED_REQUEST",
  PROOF_NOT_YET_VALID: "PROOF_NOT_YET_VALID",
  // Permit FailureCode members
  NOT_ACTIVE: "POLICY_REFUSAL",
  REVOKED: "AUTHORITY_REVOKED",
  EXPIRED: "PROOF_EXPIRED",
  SCOPE_DENIED: "POLICY_REFUSAL",
  OUT_OF_SCOPE: "POLICY_REFUSAL",
  BUDGET_EXCEEDED: "POLICY_REFUSAL",
  RATE_LIMITED: "POLICY_REFUSAL",
  ENGINE_ERROR: "OUTCOME_UNKNOWN",
};

const INTERNAL_TO_DISCLOSED: Record<string, string> = {
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  UNSUPPORTED_PROTOCOL_VERSION: "UNSUPPORTED_PROTOCOL_VERSION",
  CANONICALISATION_FAILURE: "CANONICALISATION_FAILURE",
  PROOF_MISSING: "PROOF_MISSING",
  PROOF_INVALID: "PROOF_INVALID",
  ISSUER_UNTRUSTED: "PROOF_INVALID",
  SIGNATURE_INVALID: "PROOF_INVALID",
  PROOF_EXPIRED: "PROOF_EXPIRED",
  PROOF_NOT_YET_VALID: "PROOF_NOT_YET_VALID",
  AUDIENCE_MISMATCH: "PROOF_INVALID",
  TARGET_MISMATCH: "PROOF_INVALID",
  ACTION_MISMATCH: "PROOF_INVALID",
  PARAMETER_MISMATCH: "PROOF_INVALID",
  REPLAY_DETECTED: "REPLAY_DETECTED",
  AUTHORITY_REVOKED: "AUTHORITY_REVOKED",
  POLICY_REFUSAL: "POLICY_REFUSAL",
  CREDENTIAL_UNAVAILABLE: "CREDENTIAL_UNAVAILABLE",
  PROVIDER_REFUSAL: "PROVIDER_REFUSAL",
  PROVIDER_FAILURE: "PROVIDER_FAILURE",
  OUTCOME_UNKNOWN: "OUTCOME_UNKNOWN",
};

const RETRYABLE: Record<string, boolean> = {
  MALFORMED_REQUEST: false,
  UNSUPPORTED_PROTOCOL_VERSION: false,
  CANONICALISATION_FAILURE: false,
  PROOF_MISSING: false,
  PROOF_INVALID: false,
  ISSUER_UNTRUSTED: false,
  SIGNATURE_INVALID: false,
  PROOF_EXPIRED: false,
  PROOF_NOT_YET_VALID: true,
  AUDIENCE_MISMATCH: false,
  TARGET_MISMATCH: false,
  ACTION_MISMATCH: false,
  PARAMETER_MISMATCH: false,
  REPLAY_DETECTED: false,
  AUTHORITY_REVOKED: false,
  POLICY_REFUSAL: false,
  CREDENTIAL_UNAVAILABLE: true,
  PROVIDER_REFUSAL: false,
  PROVIDER_FAILURE: true,
  OUTCOME_UNKNOWN: true,
};

export function resolveAlias(alias: string): string {
  // Try canonical first
  if (Object.values(RefusalCode).includes(alias as RefusalCode)) return alias;
  if (alias in COMPATIBILITY_ALIASES) return COMPATIBILITY_ALIASES[alias];
  throw new Error(`refusal code ${JSON.stringify(alias)} is neither canonical nor a registered alias`);
}

export function refusalToDisclosedCode(internalCode: string | null, _policy: DisclosurePolicy): string {
  if (internalCode === null) return RefusalCode.PROOF_MISSING;
  if (!(internalCode in INTERNAL_TO_DISCLOSED)) return RefusalCode.OUTCOME_UNKNOWN;
  return INTERNAL_TO_DISCLOSED[internalCode];
}

export function refusalToInternalCode(internalCode: string | null, policy: DisclosurePolicy): string | null {
  if (policy === DisclosurePolicy.PUBLIC) return null;
  return internalCode;
}

export function refusalToRetryable(internalCode: string | null): boolean {
  if (internalCode === null) return RETRYABLE[RefusalCode.PROOF_MISSING];
  if (!(internalCode in RETRYABLE)) return true;
  return RETRYABLE[internalCode];
}

export function isDisclosedCodeSafe(code: string): boolean {
  return PUBLIC_SAFE_CODES.has(code);
}

export function isDetailedCode(code: string): boolean {
  return DETAILED_CODES.has(code);
}
